### ISSUE TITLE
language-groovy not detecting shebang

### ISSUE THREAD

**Issue by bcatubig** [Jakehp/language-groovy#20]
Hi,

I have some non-standard named Groovy files that are not being detected by the plugin even with a `#!/usr/bin/env groovy` shebang.

Atom fails to correctly set the syntax. Would you be able to add in syntax detection based off of a groovy shebang?

Either 
```
#!/usr/bin/env groovy
```

or

```
#!groovy
```

**Comment by AwaNoodle** [comment]
[I've had a quick go at fixing this.](https://github.com/Jakehp/language-groovy/pull/21)

**Comment by Jakehp** [comment]
Fixed with https://github.com/Jakehp/language-groovy/pull/21
